Repository alphagov/gdx-data-share-poc, pull requests merged in 2023-02, with the labels that each got.

#401 GPC-NONE: Add new terms to glossary
  README.md
Labels: documentation

#403 GPC-106: Document retention policy
  doc/architecture/decisions/0013-event-auditing.md
  doc/architecture/decisions/0014-retention-policy.md
Labels: documentation

#437 GPC-168 Missing policy to access SSM secrets
  terraform/dev/main.tf
  terraform/modules/data-share-service/codedeploy.tf
  terraform/modules/data-share-service/ecs.tf
  terraform/modules/data-share-service/iam.tf
  terraform/modules/data-share-service/ssm.tf
Labels: bug

#434 GPC-167 Add swagger docs for new Event type for Receiving a prisoner in Prison
  src/main/kotlin/uk/gov/gdx/datashare/controllers/EventsController.kt
  src/main/kotlin/uk/gov/gdx/datashare/models/EventNotification.kt
Labels: documentation

#433 GPC-NONE: Document current architecture
  doc/architecture/architecture.drawio.svg
  doc/architecture/architecture.md
Labels: documentation

#460 GPC-NONE: Block deploy on format
  .github/workflows/infrastructure-main.yml
Labels: github_actions, merge when green

#459 Github actions test reporting
  .github/workflows/application-pull-request.yml
  .github/workflows/test.yml
Labels: github_actions, merge when green

#462 GPC-NONE: Add terraform plan concurrency
  .github/workflows/infrastructure-main.yml
  .github/workflows/infrastructure-pull-request.yml
Labels: github_actions, merge when green

#438 GPC-82: Add runbook for deployment failures
  doc/runbooks/deployment-failures.md
Labels: documentation

#470 GPC-NONE: Simplify readme
  README.md
  doc/simulating-event-flows.md
Labels: merge when green

#472 GPC-NONE: Update logback config
  src/main/resources/logback-spring.xml
Labels: merge when green

#474 GPC-NONE: Tidy workflows
  .github/workflows/application-main.yml
  .github/workflows/application-pull-request-autopass.yml
  .github/workflows/application-pull-request.yml
  .github/workflows/autopass/openapi-lint-autopass.yml
  .github/workflows/autopass/test-autopass.yml
  .github/workflows/dependabot.yml
  .github/workflows/kotlin-lint-fix-autopass.yml
  .github/workflows/kotlin-lint-fix.yml
  .github/workflows/main/build-and-push.yml
  .github/workflows/main/codedeploy.yml
  .github/workflows/pull-request/openapi-lint.yml
  .github/workflows/shared/test.yml
Labels: github_actions, merge when green

#475 GPC-NONE: Untidy workflows
  .github/dependabot.yml
  .github/workflows/application-main.yml
  .github/workflows/application-pull-request-autopass.yml
  .github/workflows/application-pull-request.yml
  .github/workflows/build-and-push.yml
  .github/workflows/codedeploy.yml
  .github/workflows/openapi-lint-autopass.yml
  .github/workflows/openapi-lint.yml
  .github/workflows/test-autopass.yml
  .github/workflows/test.yml
Labels: github_actions, merge when green

#473 GPC-93: Add in deploy hook check
  terraform/modules/deploy_hook/lambdas/hook.py
Labels: merge when green

#486 GPC-NONE: Remove unused OWASP config
  build.gradle.kts
  postgres-suppressions.xml
  reactive-suppressions.xml
Labels: merge when green

#487 GPC-NONE: Replace Mockito with Mockk
  src/test/kotlin/uk/gov/gdx/datashare/queue/AwsQueueServiceTest.kt
Labels: merge when green

#513 GPC-NONE: Clarify build.gradle labelling
  build.gradle.kts
Labels: merge when green

#512 GPC-NONE: Add starter for supplier onboarding
  doc/how-to-onboard-a-supplier.md
Labels: merge when green

#527 GPC-166: Update new environment documentation
  doc/infrastructure.md
Labels: merge when green

#553 GPC-151: Use corretto for Java distribution
  Dockerfile
Labels: merge when green
